### ISSUE TITLE
Intent Conflicts

### ISSUE THREAD

**Issue by NeonDaniel** [mikejgray/neon-homeassistant-skill#12]
"show" and "change" intents are capturing utterances intended for the [user settings skill](https://github.com/NeonGeckoCom/skill-user_settings/blob/dev/test/test_intents.yaml).

Maybe the [show.area.dashboard](https://github.com/mikejgray/neon-homeassistant-skill/blob/main/neon_homeassistant_skill/vocab/en-us/show.area.dashboard.intent) intent can be disabled or updated to solve the 'show' conflicts?

For the "change" conflict, I'm thinking its [this change brightness intent](https://github.com/mikejgray/neon-homeassistant-skill/blob/main/neon_homeassistant_skill/vocab/en-us/lights.set.brightness.intent#L3)

From @NeonClary testing:
Here is a list of the commands affected. It seems to be the prompts "change my" and "show me" that are affected. The response is versions of "An error occurred while processing a request in Neon Home Assistant Skill" or "Could not find ___ in Home Assistant skill"

Show me the time
Show me the demo
Change my units to (metric or imperial)
Change my time format to...
Change my location to...
Change my timezone to...
Change my first name to...
Change my preferred name to...
Change my primary language to...
Change my secondary language to...

**Comment by mikejgray** [comment]
Good call out! I will make adjustments to the intents - they seemed overly broad even before this report - and add tests to ensure that the reported intents do **not** match this skill.

**Comment by NeonClary** [comment]
Great, thank you! :-)
