### ISSUE TITLE
[FEAT] Helper entities need to be accessible

### ISSUE THREAD

**Issue by burnsfisher** [mikejgray/neon-homeassistant-skill#14]
If you want to have an HA automation or scene activate, the way I know how to do it is to create a helper button entity and use that as a trigger for the automation.  But as far as I can see, that helper entity is not accessible from the NHASkill.  That, or some other way to trigger scenes would be really helpful!

**Comment by mikejgray** [comment]
Hey @burnsfisher , thanks for the issue report. This is something that is actually upstream of this skill. Anything exposed by [the PHAL plugin](https://github.com/OpenVoiceOS/ovos-PHAL-plugin-homeassistant) is accessible by the voice interface (this skill). I'll take a peek at that code to see if it's easy to add, and in the meantime I intend to also PR to allow directly interfacing with Home Assistant's new Assist feature.

**Comment by mikejgray** [comment]
This is now available via the PHAL plugin GUI. Scenes are also able to be activated by voice intent, both directly and using the Assist feature.

**Comment by fermulator** [comment]
Question (follow-up) 

it seems like ultimately (after following the chain of incomplete PRs) -- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-homeassistant/pull/20 delivered scene capability

however I still don't see this `intent` here https://github.com/mikejgray/neon-homeassistant-skill/tree/main/neon_homeassistant_skill/locale/en-us/intents 

Situation/update?

**Comment by fermulator** [comment]
(ah; interesting, simply "turn on|turn off" works on "scenes"!)
