### ISSUE TITLE
[BUG] devices_list not populated

### ISSUE THREAD

**Issue by NeonDaniel** [mikejgray/neon-homeassistant-skill#20]
### Description

I've noticed some cases where it seems `devices_list` hasn't yet been populated when I make a request which just speaks a generic error message (https://github.com/mikejgray/neon-homeassistant-skill/blob/main/neon_homeassistant_skill/__init__.py#L287)

### Steps to Reproduce

- configured homeassistant via PHAL Plugin
- Update homeassistant skill to latest (0.0.11)
- Ask to turn on a light that definitely exists

### Relevant Code

I added some logging and found I'm getting to line 286:
```
         if not self.devices_list:
            return None)
```

**Comment by NeonDaniel** [comment]
This is really a bug in the plugin, but maybe the skill could speak a different error in this case?

**Comment by mikejgray** [comment]
Got it, I can probably do something a little more user-friendly. Maybe even defer until it gets the list back...although there are some edge cases to consider there.

**Comment by mikejgray** [comment]
@NeonDaniel The v.0.0.12 branch and version 0.0.12a3 on PyPi should address this. I noticed that both the PHAL plugin and the skill initiate a device list build, which is probably conflicting and slowing it down, so I removed it from the skill. Improved logged, improved spoken errors, and also an intent specifically to rebuild the list.
